whups, Snakefile 'fix' for empty prefetch output

diff --git a/genome_grist/conf/Snakefile b/genome_grist/conf/Snakefile
--- a/genome_grist/conf/Snakefile
+++ b/genome_grist/conf/Snakefile
@@ -879,9 +879,9 @@ rule sourmash_prefetch_wc:
         sig = outdir + "/sigs/{sample}.abundtrim.sig.zip",
         db = SOURMASH_DB_LIST,
     output:
-        csv = outdir + "/gather/{sample}.prefetch.csv",
-        known = outdir + "/gather/{sample}.known.sig.zip",
-        unknown = outdir + "/gather/{sample}.unknown.sig.zip",
+        csv = touch(outdir + "/gather/{sample}.prefetch.csv"),
+        known = touch(outdir + "/gather/{sample}.known.sig.zip"),
+        unknown = touch(outdir + "/gather/{sample}.unknown.sig.zip"),
     resources:
         mem_mb=int(PREFETCH_MEMORY / 1e3)
     conda: "env/sourmash.yml"
@@ -939,6 +939,12 @@ rule sourmash_gather_wc:
         moltype = f"--{SOURMASH_COMPUTE_TYPE.lower()}",
         threshold_bp = SOURMASH_DATABASE_THRESHOLD_BP,
     shell: """
+        if [ ! -s {input.picklist} ]; then
+            echo "** ERROR: prefetch didn't find anything for sample '{wildcards.sample}'"
+            echo "** That means there are no matches to anything in the database for that sample!"
+            echo "** You'll need to change either your database or remove your sample :("
+            exit 1
+        fi
         sourmash gather {input.sig} {input.db} -o {output.csv} \
           --threshold-bp {params.threshold_bp} \
           --picklist {input.picklist}::prefetch \
